spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.103.247:3306/pet?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: YJX794BPRmNjjNdA
  servlet:
      multipart:
          enabled: true
          max-file-size: 5MB
          max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapping/*.xml

server:
  port: 8000

local-file-store-path: D:\img\

pagehelper:
    ## pagehelper分页插件配置 ##
    #标识是哪一种数据库
    helperDialect: mysql
    #如果 pageSize=0 就会查询出全部的结果（相当于没有执行分页查询）
    page-size-zero: true
    #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
    params: count=countSql
    # true启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
    reasonable: false
    supportMethodsArguments: true

swagger:
  enabled: true
  version: "1.0"
  title: "养宠记帐"
  base-package: "com.july.pet.controller"